VERSION 0.8
IMPORT ./../.. AS base 
IMPORT github.com/earthly/lib/rust:3.0.3 AS rust

test-native-base:
    FROM base+rust --toolchain=nightly
    COPY (base+install-tool/tool --tool=cargo-nextest) /bin/cargo-nextest
    COPY --keep-ts base+workspace-src/src .

test-native-dev:
    FROM +test-native-base
    DO rust+CARGO --args="nextest run --all-features -p natrix"

test-native-release:
    FROM +test-native-base
    DO rust+CARGO --args="nextest run --all-features -p natrix --cargo-profile test-no-assertions"

test-web:
    ARG --required toolchain
    FROM base+wasm --toolchain=$toolchain


    COPY (base+install-tool/tool --tool=wasm-pack) /bin/wasm-pack
    COPY --keep-ts base+workspace-src/src .

    DO rust+SET_CACHE_MOUNTS_ENV
    RUN --mount=$EARTHLY_RUST_TARGET_CACHE \
        cd ./crates/natrix && wasm-pack test --headless --chrome --features test_utils --features console_log \
        $(if [ "$toolchain" = "nightly" ]; then echo "--all-features"; fi)

check:
    ARG --required toolchain
    FROM base+with-clippy --toolchain=$toolchain
    COPY (base+install-tool/tool --tool=cargo-hack) /bin/cargo-hack
    COPY --keep-ts base+workspace-src/src .

    IF [ "$toolchain" = "nightly" ]
        ENV EXTRA_ARGS=""
    ELSE
        ENV EXTRA_ARGS="--skip nightly"
    END
    DO rust+SET_CACHE_MOUNTS_ENV --target_cache_suffix=$toolchain
    RUN --mount=$EARTHLY_RUST_TARGET_CACHE \ 
        cargo hack clippy -p natrix --each-feature --tests $EXTRA_ARGS -- -Dwarnings

cargo-deny:
    FROM base+rust --toolchain=nightly
    COPY (base+install-tool/tool --tool=cargo-deny) /bin/cargo-deny
    COPY --keep-ts base+workspace-src/src .

    DO rust+SET_CACHE_MOUNTS_ENV
    RUN --mount=$EARTHLY_RUST_TARGET_CACHE \
        cd ./crates/natrix && cargo-deny check --exclude-dev 

all:
    BUILD +test-native-dev
    BUILD +test-native-release
    BUILD +test-web --toolchain=stable
    BUILD +test-web --toolchain=nightly
    BUILD +check --toolchain=stable
    BUILD +check --toolchain=nightly
    BUILD +cargo-deny
    
