VERSION 0.8
IMPORT ./../.. AS base 
IMPORT github.com/earthly/lib/rust:3.0.3 AS rust

check:
    FROM base+with-clippy --toolchain=stable
    COPY --keep-ts base+workspace-src/src .
    DO rust+CARGO --args="clippy -p natrix-cli -- -Dwarnings"

cargo-deny:
    FROM base+rust --toolchain=stable
    COPY (base+install-tool/tool --tool=cargo-deny) /bin/cargo-deny
    COPY --keep-ts base+workspace-src/src .

    DO rust+SET_CACHE_MOUNTS_ENV
    RUN --mount=$EARTHLY_RUST_TARGET_CACHE \
        cd ./crates/natrix-cli && cargo-deny check --exclude-dev 

build-cli:
    FROM base+rust --toolchain=stable
    COPY --keep-ts base+workspace-src/src .

    DO rust+SET_CACHE_MOUNTS_ENV
    RUN rm ./target/debug/natrix* | true
    RUN --mount=$EARTHLY_RUST_TARGET_CACHE rm ./target/debug/natrix* | true
    DO rust+CARGO --args="build -p natrix-cli" --output="debug/natrix"
    SAVE ARTIFACT ./target/debug/natrix natrix

test-project-gen:
    ARG --required toolchain
    FROM base+wasm --toolchain=$toolchain
    COPY (base+install-tool/tool --tool=wasm-pack) /bin/wasm-pack
    COPY +build-cli/natrix /bin/natrix

    ENV NATRIX_PATH=/workspace/crates/natrix
    IF [ "$toolchain" = "nightly" ]
        RUN natrix new hello
    ELSE
        RUN natrix new hello --stable
    END

    COPY --keep-ts base+workspace-src/src /workspace

    WORKDIR ./hello

    DO rust+SET_CACHE_MOUNTS_ENV --target_cache_suffix=$toolchain
    RUN --mount=$EARTHLY_RUST_TARGET_CACHE natrix build
    RUN --mount=$EARTHLY_RUST_TARGET_CACHE wasm-pack test --headless --chrome

all:
    BUILD +check
    BUILD +cargo-deny
    BUILD +test-project-gen --toolchain=nightly
    BUILD +test-project-gen --toolchain=stable
